In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import os
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\musth\appd

In [2]:
df = pd.read_csv('data.csv')
df = pd.DataFrame(df)
#df[['fuel_cost_6000_miles']]
df

c:\users\musth\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (6,30) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


file  year manufacturer  \
0                     DatapartC_july2000.csv  2000   Alfa Romeo   
1                     DatapartC_july2000.csv  2000   Alfa Romeo   
2                     DatapartC_july2000.csv  2000   Alfa Romeo   
3                     DatapartC_july2000.csv  2000   Alfa Romeo   
4                     DatapartC_july2000.csv  2000   Alfa Romeo   
...                                      ...   ...          ...   
45506  download-data-for-Aug-2013-Euro-6.csv  2013   Volkswagen   
45507  download-data-for-Aug-2013-Euro-6.csv  2013   Volkswagen   
45508  download-data-for-Aug-2013-Euro-6.csv  2013   Volkswagen   
45509  download-data-for-Aug-2013-Euro-6.csv  2013   Volkswagen   
45510  download-data-for-Aug-2013-Euro-6.csv  2013   Volkswagen   

               model                       description  euro_standard  \
0          145 Range                1.6 Twin Spark 16v              2   
1          145 Range                1.8 Twin Spark 16v              2   
2          145 Range                        Cloverleaf              2   
3          146 Range                1.6 Twin Spark 16v              2   
4          146 Range                1.8 Twin Spark 16v              2   
...              ...                               ...            ...   
45506  New Golf 2013          2.0 TDI 184PS 5 door DSG              6   
45507  New Golf 2013      GTI 2.0 TSI 220PS 3 / 5 door              6   
45508  New Golf 2013      GTI 2.0 TSI 230PS 3 / 5 door              6   
45509  New Golf 2013  GTI 2.0 TSI 220PS 3 / 5 door DSG              6   
45510  New Golf 2013  GTI 2.0 TSI 230PS 3 / 5 door DSG              6   

      tax_band transmission transmission_type  engine_capacity  ...  \
0          NaN           M5            Manual           1598.0  ...   
1          NaN           M5            Manual           1747.0  ...   
2          NaN           M5            Manual           1970.0  ...   
3          NaN           M5            Manual           1598.0  ...   
4          NaN           M5            Manual           1747.0  ...   
...        ...          ...               ...              ...  ...   
45506        D           D6               NaN           1968.0  ...   
45507        E           M6               NaN           1984.0  ...   
45508        E           M6               NaN           1984.0  ...   
45509        F           D6               NaN           1984.0  ...   
45510        F           D6               NaN           1984.0  ...   

      nox_emissions  thc_nox_emissions  particulates_emissions  \
0               NaN                NaN                     NaN   
1               NaN                NaN                     NaN   
2               NaN                NaN                     NaN   
3               NaN                NaN                     NaN   
4               NaN                NaN                     NaN   
...             ...                ...                     ...   
45506          74.0              108.0                     0.0   
45507          38.0               35.0                     NaN   
45508          38.0               35.0                     NaN   
45509          54.0               32.0                     NaN   
45510          54.0               32.0                     NaN   

       fuel_cost_12000_miles  fuel_cost_6000_miles  standard_12_months  \
0                        NaN                 618.0                 NaN   
1                        NaN                 633.0                 NaN   
2                        NaN                 663.0                 NaN   
3                        NaN                 626.0                 NaN   
4                        NaN                 633.0                 NaN   
...                      ...                   ...                 ...   
45506                 1316.0                   NaN                 NaN   
45507                 1598.0                   NaN                 NaN   
45508                 1598.0                  

In [3]:
#KE BAWAH Pemodelan Konsumsi Bahan Bakar Kendaraan
df = pd.read_csv('measurements.csv')
df = pd.DataFrame(df)
df.index = df.index + 1
df = df[['distance', 'consume', 'speed']]

In [5]:
# model for predict consumetion with linear regression distance and consume
df_1 = df[['distance', 'consume']]
DataX = df[['distance']]
DataX = DataX.values
DataY = df[['consume']]
DataY = DataY.values

# making import
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

# divide data into train and test
train_size = int(len(DataX) * 0.7)
test_size = len(DataX) - train_size
train, test = DataX[0:train_size,:], DataX[train_size:len(DataX),:]
print(len(train), len(test))

train_size_y = int(len(DataY) * 0.7)
test_size_y = len(DataY) - train_size_y
train_y, test_y = DataY[0:train_size_y,:], DataY[train_size_y:len(DataY),:]
print(len(train_y), len(test_y))


271 117
271 117


In [6]:
DataY = pd.DataFrame(DataY)
DataY.to_csv (r'newdatay.csv', index = None, header=True)

In [7]:
# Arsitektur model 
Datanew = pd.read_csv('newdata.csv')
datanewy = pd.read_csv('newdatay.csv')
datanewy

0
0      5
1    4,2
2    5,5
3    3,9
4    4,5
..   ...
383  3,7
384  4,3
385  3,8
386  4,6
387    5

[388 rows x 1 columns]

In [44]:
Y = []
filepath = 'newdatay.csv'
with open(filepath) as fp:
   line = fp.readline()
   cnt = 1
   while line:
       print("Line {}: {}".format(cnt, line.strip()))
       Y.append(float(line.strip()))
       line = fp.readline()
       cnt += 1
print (Y)

Line 1: 0
Line 2: 5
Line 3: 4.2
Line 4: 5.5
Line 5: 3.9
Line 6: 4.5
Line 7: 6.4
Line 8: 4.4
Line 9: 5
Line 10: 6.4
Line 11: 5.3
Line 12: 5.6
Line 13: 4.6
Line 14: 5.9
Line 15: 5.1
Line 16: 4.7
Line 17: 5.1
Line 18: 5.6
Line 19: 5.1
Line 20: 4.9
Line 21: 4.7
Line 22: 5.5
Line 23: 5.9
Line 24: 5.7
Line 25: 4.7
Line 26: 5.9
Line 27: 4.1
Line 28: 5.7
Line 29: 5.8
Line 30: 5.5
Line 31: 5.7
Line 32: 5.3
Line 33: 5
Line 34: 5.6
Line 35: 4.8
Line 36: 4.3
Line 37: 5.7
Line 38: 5.2
Line 39: 7.4
Line 40: 4.8
Line 41: 6.5
Line 42: 4
Line 43: 5
Line 44: 4.6
Line 45: 4.3
Line 46: 3.3
Line 47: 9.9
Line 48: 5.1
Line 49: 4.9
Line 50: 4.9
Line 51: 4.7
Line 52: 5.1
Line 53: 4.9
Line 54: 4.2
Line 55: 6.1
Line 56: 6.4
Line 57: 4.9
Line 58: 4.9
Line 59: 6.2
Line 60: 4.2
Line 61: 5.7
Line 62: 7.9
Line 63: 12.2
Line 64: 5.8
Line 65: 5.3
Line 66: 5.4
Line 67: 4.7
Line 68: 4.6
Line 69: 5.4
Line 70: 4.3
Line 71: 4.5
Line 72: 5.2
Line 73: 6.2
Line 74: 5.1
Line 75: 3.9
Line 76: 5
Line 77: 5.4
Line 78: 4.5
Line 79:

In [45]:
X = []
filepath = 'newdata.csv'
with open(filepath) as fp:
   line = fp.readline()
   cnt = 1
   while line:
       print("Line {}: {}".format(cnt, line.strip()))
       X.append(float(line.strip()))
       line = fp.readline()
       cnt += 1
print (X)


Line 1: 0
Line 2: 28
Line 3: 12
Line 4: 11.2
Line 5: 12.9
Line 6: 18.5
Line 7: 8.3
Line 8: 7.8
Line 9: 12.3
Line 10: 4.9
Line 11: 11.9
Line 12: 12.4
Line 13: 11.8
Line 14: 12.3
Line 15: 24.7
Line 16: 12.4
Line 17: 17.3
Line 18: 33.4
Line 19: 11.8
Line 20: 25.9
Line 21: 11.8
Line 22: 25.3
Line 23: 14.2
Line 24: 17.9
Line 25: 11.8
Line 26: 12.3
Line 27: 12.4
Line 28: 18.4
Line 29: 18.4
Line 30: 18.3
Line 31: 18.4
Line 32: 12.3
Line 33: 11.8
Line 34: 12.3
Line 35: 32.6
Line 36: 19
Line 37: 12.1
Line 38: 20
Line 39: 4.9
Line 40: 11.8
Line 41: 12.3
Line 42: 12.4
Line 43: 4.5
Line 44: 11.7
Line 45: 10.2
Line 46: 5.4
Line 47: 2
Line 48: 14.2
Line 49: 16
Line 50: 11.8
Line 51: 27.3
Line 52: 11.8
Line 53: 10.6
Line 54: 11.6
Line 55: 13.1
Line 56: 6.1
Line 57: 153.5
Line 58: 11.8
Line 59: 12.3
Line 60: 12.4
Line 61: 12.3
Line 62: 2.9
Line 63: 2.1
Line 64: 9.8
Line 65: 6.8
Line 66: 12.4
Line 67: 12.4
Line 68: 11.8
Line 69: 12.3
Line 70: 14
Line 71: 11.8
Line 72: 12.3
Line 73: 2
Line 74: 13.9
Line

In [46]:
xdata = []
for x in X:
    xdata.append(int(x))

In [47]:
ydata = []
for x in Y:
    ydata.append(int(x))

In [49]:
for x in Y:
    print (type(x))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class '

In [50]:
Y = np.array(Y)
print (Y.shape)
T = Y.reshape((Y.shape[0], 1))
print (T.shape)

(389,)
(389, 1)


In [51]:
X = np.array(X)
print (X.shape)
Tx = X.reshape((X.shape[0], 1))
print (T.shape)

(389,)
(389, 1)


In [52]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(T)

In [53]:
scaler = MinMaxScaler(feature_range=(0, 1))
dataseta = scaler.fit_transform(Tx)

In [54]:
Tx

array([[  0. ],
       [ 28. ],
       [ 12. ],
       [ 11.2],
       [ 12.9],
       [ 18.5],
       [  8.3],
       [  7.8],
       [ 12.3],
       [  4.9],
       [ 11.9],
       [ 12.4],
       [ 11.8],
       [ 12.3],
       [ 24.7],
       [ 12.4],
       [ 17.3],
       [ 33.4],
       [ 11.8],
       [ 25.9],
       [ 11.8],
       [ 25.3],
       [ 14.2],
       [ 17.9],
       [ 11.8],
       [ 12.3],
       [ 12.4],
       [ 18.4],
       [ 18.4],
       [ 18.3],
       [ 18.4],
       [ 12.3],
       [ 11.8],
       [ 12.3],
       [ 32.6],
       [ 19. ],
       [ 12.1],
       [ 20. ],
       [  4.9],
       [ 11.8],
       [ 12.3],
       [ 12.4],
       [  4.5],
       [ 11.7],
       [ 10.2],
       [  5.4],
       [  2. ],
       [ 14.2],
       [ 16. ],
       [ 11.8],
       [ 27.3],
       [ 11.8],
       [ 10.6],
       [ 11.6],
       [ 13.1],
       [  6.1],
       [153.5],
       [ 11.8],
       [ 12.3],
       [ 12.4],
       [ 12.3],
       [  2.9],
       [

In [55]:
T.shape

(389, 1)

In [56]:
dataseta

array([[0.        ],
       [0.12956964],
       [0.05552985],
       [0.05182786],
       [0.05969459],
       [0.08560851],
       [0.03840814],
       [0.0360944 ],
       [0.05691809],
       [0.02267469],
       [0.0550671 ],
       [0.05738084],
       [0.05460435],
       [0.05691809],
       [0.11429894],
       [0.05738084],
       [0.08005553],
       [0.15455807],
       [0.05460435],
       [0.11985192],
       [0.05460435],
       [0.11707543],
       [0.06571032],
       [0.08283202],
       [0.05460435],
       [0.05691809],
       [0.05738084],
       [0.08514577],
       [0.08514577],
       [0.08468302],
       [0.08514577],
       [0.05691809],
       [0.05460435],
       [0.05691809],
       [0.15085609],
       [0.08792226],
       [0.0559926 ],
       [0.09254975],
       [0.02267469],
       [0.05460435],
       [0.05691809],
       [0.05738084],
       [0.02082369],
       [0.0541416 ],
       [0.04720037],
       [0.02498843],
       [0.00925497],
       [0.065

In [57]:
dataset

array([[0.        ],
       [0.40983607],
       [0.3442623 ],
       [0.45081967],
       [0.31967213],
       [0.36885246],
       [0.52459016],
       [0.36065574],
       [0.40983607],
       [0.52459016],
       [0.43442623],
       [0.45901639],
       [0.37704918],
       [0.48360656],
       [0.41803279],
       [0.3852459 ],
       [0.41803279],
       [0.45901639],
       [0.41803279],
       [0.40163934],
       [0.3852459 ],
       [0.45081967],
       [0.48360656],
       [0.46721311],
       [0.3852459 ],
       [0.48360656],
       [0.33606557],
       [0.46721311],
       [0.47540984],
       [0.45081967],
       [0.46721311],
       [0.43442623],
       [0.40983607],
       [0.45901639],
       [0.39344262],
       [0.35245902],
       [0.46721311],
       [0.42622951],
       [0.60655738],
       [0.39344262],
       [0.53278689],
       [0.32786885],
       [0.40983607],
       [0.37704918],
       [0.35245902],
       [0.2704918 ],
       [0.81147541],
       [0.418

In [58]:
dataseta.shape

(389, 1)

In [60]:
# linear try
model = tf.keras.models.Sequential(
    [tf.keras.layers.Dense(units=64, input_shape=[1], activation='relu')])
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(64, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy', 'mse'])
model.fit(dataseta, dataset, epochs=1250)

ValueError: A target array with shape (389, 1) was passed for an output of shape (None, 64) while using as loss `binary_crossentropy`. This loss expects targets to have the same shape as the output.

In [341]:
y = model.predict([12])
Y = scaler.inverse_transform(y)
print (Y)

[[12.199999]]


In [226]:
'''
# make predictions
trainPredict = model.predict(dataseta)
testPredict = model.predict(dataset)
# invert predictions
trainPredict = scaler.inverse_transform(trainPredict)
trainY = scaler.inverse_transform([trainY])
testPredict = scaler.inverse_transform(testPredict)
testY = scaler.inverse_transform([testY])
# calculate root mean squared error
trainScore = math.sqrt(mean_squared_error(trainY[0], trainPredict[:,0]))
print('Train Score: %.2f RMSE' % (trainScore))
testScore = math.sqrt(mean_squared_error(testY[0], testPredict[:,0]))
print('Test Score: %.2f RMSE' % (testScore))
'''
Y = scaler.inverse_transform(y)
print (Y)

[[-9.47981]]


# Model 2

In [258]:
keluaran = T

In [259]:
masukan = Tx

In [282]:
masukan.shape

(389, 1)

In [262]:
keluaran.shape

(389, 1)

In [285]:
a = keluaran[1:2,0]
a

array([5.])

In [308]:
# Create Datasets
dataload = masukan
ax = np.array([1, 2, 3])
ay = np.array([5, 7, 9])
dataX, dataY = []
# convert an array of values into a dataset matrix
def create_dataset(value, look_back=1):
    for i in range(len(value)):
        for x in value:
            a = ax[(i-1):i, 0]
            dataX.append(a)
            dataY.append(x)
create_dataset(ay, 1)

ValueError: not enough values to unpack (expected 2, got 0)

In [266]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
m_n = scaler.fit_transform(masukan)
k_n = scaler.fit_transform(keluaran)

In [270]:
m_n_train = m_n[:300,]
m_n_test = m_n[300:,]
print (m_n_test.shape)
print (m_n_train.shape)

(89, 1)
(300, 1)


In [309]:
k_n_train = k_n[:300,]
k_n_test = k_n[300:,]
print (k_n_test.shape)
print (k_n_train.shape)

(89, 1)
(300, 1)


In [ ]:
# reshape input to be [samples, time steps, features]
trainX = numpy.reshape(m_n, (trainX.shape[0], 1, trainX.shape[1]))
testX = numpy.reshape(, (testX.shape[0], 1, testX.shape[1]))

# New Data 

In [125]:
import pandas as pd
yt = pd.read_excel('measurements2.xlsx')
pd = yt[['distance', 'consume', 'speed']]
pd

distance  consume  speed
0        28.0      5.0     26
1        12.0      4.2     30
2        11.2      5.5     38
3        12.9      3.9     36
4        18.5      4.5     46
..        ...      ...    ...
383      16.0      3.7     39
384      16.1      4.3     38
385      16.0      3.8     45
386      15.4      4.6     42
387      14.7      5.0     25

[388 rows x 3 columns]

In [126]:
pd.shape

(388, 3)

In [127]:
train = pd[:300]
test = pd[300:]

train = train.values
test  = test.values

train

array([[ 28. ,   5. ,  26. ],
       [ 12. ,   4.2,  30. ],
       [ 11.2,   5.5,  38. ],
       [ 12.9,   3.9,  36. ],
       [ 18.5,   4.5,  46. ],
       [  8.3,   6.4,  50. ],
       [  7.8,   4.4,  43. ],
       [ 12.3,   5. ,  40. ],
       [  4.9,   6.4,  26. ],
       [ 11.9,   5.3,  30. ],
       [ 12.4,   5.6,  42. ],
       [ 11.8,   4.6,  38. ],
       [ 12.3,   5.9,  59. ],
       [ 24.7,   5.1,  58. ],
       [ 12.4,   4.7,  46. ],
       [ 17.3,   5.1,  24. ],
       [ 33.4,   5.6,  36. ],
       [ 11.8,   5.1,  32. ],
       [ 25.9,   4.9,  39. ],
       [ 11.8,   4.7,  40. ],
       [ 25.3,   5.5,  32. ],
       [ 14.2,   5.9,  38. ],
       [ 17.9,   5.7,  37. ],
       [ 11.8,   4.7,  36. ],
       [ 12.3,   5.9,  62. ],
       [ 12.4,   4.1,  57. ],
       [ 18.4,   5.7,  21. ],
       [ 18.4,   5.8,  28. ],
       [ 18.3,   5.5,  29. ],
       [ 18.4,   5.7,  35. ],
       [ 12.3,   5.3,  51. ],
       [ 11.8,   5. ,  29. ],
       [ 12.3,   5.6,  58. ],
       [ 3

In [136]:
pf = yt[['distance','speed']]
pg = yt[['consume']]
pf = pf.values
pg = pg.values
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
p_f = scaler.fit_transform(pf)
p_g = scaler.fit_transform(pg)

trainx = p_f[:360]
trainy = p_g[:360]
testx = p_f[360:]
testy = p_f[360:]
len(testy)

28

In [137]:
from keras.layers import Dense
from keras.models import Sequential
print ()

In [151]:
model2 = Sequential(
    [Dense(units=256, input_shape=[2, ], activation='relu')])
model2.add(Dense(200, activation='relu'))
model2.add(Dense(128, activation='relu'))
model2.add(Dense(128, activation='relu'))
model2.add(Dense(128, activation='relu'))
model2.add(Dense(128, activation='relu'))
model2.add(Dense(1, activation='sigmoid'))
model2.compile(optimizer='adam', loss='mse', metrics=['accuracy', 'mse'])
model2.summary()

Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_101 (Dense)            (None, 256)               768       
_________________________________________________________________
dense_102 (Dense)            (None, 200)               51400     
_________________________________________________________________
dense_103 (Dense)            (None, 128)               25728     
_________________________________________________________________
dense_104 (Dense)            (None, 128)               16512     
_________________________________________________________________
dense_105 (Dense)            (None, 128)               16512     
_________________________________________________________________
dense_106 (Dense)            (None, 128)               16512     
_________________________________________________________________
dense_107 (Dense)            (None, 1)               

In [152]:
history = model2.fit(trainx, trainy, epochs=1250, validation_data=(testx, testy))

ValueError: Error when checking target: expected dense_107 to have shape (1,) but got array with shape (2,)

In [132]:
from pandas import DataFrame
hist = DataFrame(history.history)
hist['epoch'] = history.epoch
hist.tail()

val_loss  val_accuracy   val_mse      loss  accuracy       mse  epoch
1245  0.012089           0.0  0.012089  0.006759  0.005556  0.006759   1245
1246  0.009195           0.0  0.009195  0.007377  0.005556  0.007377   1246
1247  0.011392           0.0  0.011392  0.007094  0.005556  0.007094   1247
1248  0.010920           0.0  0.010920  0.006858  0.005556  0.006858   1248
1249  0.009269           0.0  0.009269  0.006744  0.005556  0.006744   1249

In [133]:
score = model2.evaluate(testx, testy)
print("Test score: ", score[0])
print("Test accuracy: ", score[1])

28/28 [==============================] - 0s 107us/step
Test score:  0.009268890134990215
Test accuracy:  0.0


In [115]:
y = model.predict([9])
Y = scaler.inverse_transform(y)
print (Y)

[[7.95215   8.587617  6.8639774 7.565739  8.076073  7.9948006 8.083664
  7.301867  7.7200522 8.668179  7.246714  7.420486  8.521076  8.18481
  7.9719005 7.623727  7.643108  6.767503  8.348076  7.9706635 7.515248
  8.384971  7.4064674 7.117755  8.181075  8.676427  7.3626757 7.714187
  7.3537607 7.182372  7.330241  7.688628  7.9188395 7.0794077 8.4978895
  8.741046  7.396305  8.060295  7.587733  8.2267685 7.295041  7.667387
  8.2827835 8.318855  8.192261  7.267368  7.952191  8.594034  8.446465
  7.1218853 8.042263  7.72626   8.494806  7.739089  8.449775  7.919006
  7.6559916 7.6554246 7.506213  8.000495  7.746508  7.463847  7.650478
  7.14034  ]]


In [134]:
p = model2.predict([7.8])
p = scaler.inverse_transform(p)
print (p)

[[3.8235843]]


In [348]:

import tensorflow as tf
import numpy as np
# Create a simple Keras model.
x = [-1, 0, 1, 2, 3, 4]
y = [-3, -1, 1, 3, 5, 7]
t = np.random.randint(1, 100, 100)
y = []
for x in t:
    a = x*2 + 10
    y.append(a)


SyntaxError: invalid syntax (<ipython-input-348-f8394c676623>, line 7)

In [358]:
tnew = np.reshape((t.shape[0], 1))
tnew.shape

TypeError: _reshape_dispatcher() missing 1 required positional argument: 'newshape'

In [352]:
y = np.array(y)
y = np.reshape(y.shape[0])
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
tt = scaler.fit_transform(t)
ty = scaler.fit_transform(y)

ValueError: Expected 2D array, got 1D array instead:
array=[84. 42. 84. 76. 58. 61.  6. 98.  1. 59.  6. 95. 25. 98. 35. 37. 13.  9.
 40. 73. 38. 16. 30. 88. 31. 99. 56. 26. 69.  2. 42. 23. 12. 78.  6. 25.
 98. 49. 66.  9. 40. 87. 46. 73. 30. 84. 44. 59. 83. 46. 61. 17. 58. 35.
 91. 51. 56. 84. 76.  7. 93. 64. 70.  8. 21. 22. 82. 97. 33. 98.  7. 36.
 91. 32. 31. 63. 46. 39. 98. 31. 55. 55. 24. 71. 98. 56. 47. 34. 87. 16.
 36.  4. 22. 72. 76. 30. 57.  7. 93. 84.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [351]:
model = tf.keras.models.Sequential(
    [tf.keras.layers.Dense(units=1, input_shape=[1])])
model.compile(optimizer='sgd', loss='mean_squared_error')
model.fit(t, y, epochs=100)
print (model.predict([10.0]))

Train on 100 samples
Epoch 1/100
100/100 [==============================] - 0s 1ms/sample - loss: 129721134565792.3594
Epoch 2/100
100/100 [==============================] - 0s 50us/sample - loss: 95747963992204694447749857280.0000
Epoch 3/100
100/100 [==============================] - 0s 50us/sample - loss: inf                             
Epoch 4/100
100/100 [==============================] - 0s 40us/sample - loss: inf
Epoch 5/100
100/100 [==============================] - 0s 39us/sample - loss: inf
Epoch 6/100
100/100 [==============================] - 0s 40us/sample - loss: nan
Epoch 7/100
100/100 [==============================] - 0s 30us/sample - loss: nan
Epoch 8/100
100/100 [==============================] - 0s 40us/sample - loss: nan
Epoch 9/100
100/100 [==============================] - 0s 50us/sample - loss: nan
Epoch 10/100
100/100 [==============================] - 0s 50us/sample - loss: nan
Epoch 11/100
100/100 [==============================] - 0s 30us/sample - loss: nan